package main

import (
	"context"
	"fmt"
	"log"
	"os"

	// Loads variables from .env into os.Getenv(...) automatically.
	_ "github.com/joho/godotenv/autoload"
	"go-sqlc/internal/database"
	"github.com/jackc/pgx/v5/pgxpool"
)

func run() error {
	// Context is passed to every DB call so we can cancel/timeout later if needed.
	ctx := context.Background()

	// DATABASE_URL example:
	// postgres://postgres:qwer@localhost:5432/sqltest?sslmode=disable
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		return fmt.Errorf("DATABASE_URL is not set")
	}

	// sqlc is configured for pgx/v5, so use a native pgx pool.
	db, err := pgxpool.New(ctx, dsn)
	if err != nil {
		return fmt.Errorf("open connection: %w", err)
	}
	defer db.Close()

	// Ping forces an actual connection attempt now.
	if err := db.Ping(ctx); err != nil {
		return fmt.Errorf("ping database: %w", err)
	}

	// database.New(...) is generated by sqlc from query.sql.
	// It gives us type-safe Go functions for our SQL queries.
	queries := database.New(db)

	// Read example: fetch all authors from DB.
	authors, err := queries.ListAuthors(ctx)
	if err != nil {
		return fmt.Errorf("list authors: %w", err)
	}

	fmt.Printf("Connected successfully. Authors in DB: %d\n", len(authors))

	// Write example: insert one new author row.
	createdAuthor, err := queries.CreateAuthor(ctx, database.CreateAuthorParams{
		Name:     "Naabu",
		Bio:      "Naabu, a powerful port enumeration tool",
		Username: "Labubu version 4",
	})

	if err != nil {
		return fmt.Errorf("Create author: %w", err)
	}

	fmt.Printf("Created author successfully: %s\n", createdAuthor.Username)

	return nil
}

func main() {
	// Keep main small: run app logic and fail fast on error.
	if err := run(); err != nil {
		log.Fatal(err)
	}
}
